baseURL: "https://example.com/"
title: "Mario Liguori"
theme: "papermod"
languageCode: en-us

enableEmoji: true

params:
  defaultTheme: auto

  
  profileMode:
    enabled: true
    # title: "<Title>" # optional default will be site title
    subtitle: "CS Student & FOSS Lover"
    # buttons:
    #   - name: Archive
    #     url: "/archive"
    #   - name: Github
    #     url: "https://github.com/"

  # env: "production"
  author: "Mario Liguori"
  description: "Mario's personal website and blog"

  DateFormat: "January 2, 2006"
    
  socialIcons: # optional
    - name: "github"
      url: "https://github.com/archer-65"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/mario-liguori/"
    - name: "email"
      url: "mailto:mario.liguori.056@gmail.com"

  # Minor tweaks for viewers      
  ShowShareButtons: true
  ShareButtons: ["facebook", "whatsapp", "telegram", "twitter", "reddit", "linkedin"] 
  
  ShowReadingTime: true
  ShowToc: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    # - identifier: posts
    #   name: Posts
    #   url: /posts
    #   weight: 10
    - identifier: search
      name: Search
      url: /search
      weight: 20
    - identifier: archives
      name: Archive
      url: /archives
      weight: 30
    - identifier: about
      name: About me
      url: /about
      weight: 40